application: imagedatastore
version: 1
runtime: go
api_version: go1

handlers:
- url: /robots.txt
  static_files: files/robots.txt
  upload: files/robots.txt
- url: /upload
  script: _go_app
  login: admin
- url: /doupload
  script: _go_app
  login: admin
- url: /.*
  script: _go_app
